from selenium.webdriver.common.by import By

class AuthLocators:
   AUTH_EMAIL = (By.ID, "username")
   AUTH_PHONE = (By.ID, "username")
   AUTH_LOGIN = (By.ID, "username")
   AUTH_ACCOUNT = (By.CLASS_NAME, "rt-input__input")
   AUTH_PASS = (By.ID, "password")
   AUTH_BTN = (By.ID, "kc-login")
   AUTH_BTN_EMAIL = (By.ID, "t-btn-tab-mail")
   AUTH_BTN_LOGIN = (By.ID, "t-btn-tab-login")
   AUTH_BTN_ACC = (By.ID, "t-btn-tab-ls")
   AUTH_BTN_VK = (By.ID, "oidc_vk")
   AUTH_BTN_OK = (By.ID, "oidc_ok")
   AUTH_BTN_MAIL = (By.ID, "oidc_mail")
   AUTH_BTN_YANDEX = (By.ID, "oidc_ya")
   AUTH_EMAIL_OK = (By.ID, "field_email")
   AUTH_PASSWORD_OK = (By.ID, "field_password")
   AUTH_OK_SIGN_IN = (By.CLASS_NAME, "button-pro")
   AUTH_VK_EMAIL = (By.CLASS_NAME, "vkuiInput__el")
   AUTH_VK_SIGN_IN = (By.CLASS_NAME, "vkuiButton__in")
   AUTH_EMAIL_MAIL = (By.ID, "login")
   AUTH_PASSWORD_MAIL = (By.ID, "password")
   AUTH_MAIL_SIGN_IN = (By.CLASS_NAME, "ui-button-main")
   AUTH_EMAIL_YANDEX = (By.ID, "passp-field-phone")
   AUTH_YANDEX_SIGN_IN = (By.ID, "passp:phone:controls:next")
